SELECOES = [
    "🇦🇷 Argentina",
    "🇦🇺 Austrália",
    "🇧🇷 Brasil",
    "🇨🇦 Canadá",
    "🇨🇱 Chile",
    "🇨🇴 Colômbia",
    "🇰🇷 Coreia do Sul",
    "🇨🇷 Costa Rica",
    "🇭🇷 Croácia",
    "🇩🇰 Dinamarca",
    "🇪🇨 Equador",
    "🇪🇬 Egito",
    "🇪🇸 Espanha",
    "🇺🇸 Estados Unidos",
    "🇫🇷 França",
    "🏴 Inglaterra",
    "🇮🇹 Itália",
    "🇯🇵 Japão",
    "🇲🇽 México",
    "🇲🇦 Marrocos",
    "🇳🇱 Holanda",
    "🇳🇿 Nova Zelândia",
    "🇵🇾 Paraguai",
    "🇵🇪 Peru",
    "🇵🇹 Portugal",
    "🇩🇪 Alemanha",
    "🇺🇾 Uruguai",
    "🇻🇪 Venezuela"
]