SELECOES = [
    "🇨🇦 Canadá",
    "🇺🇸 Estados Unidos",
    "🇲🇽 México",
    "🇿🇦 África do Sul",
    "🇩🇪 Alemanha",
    "🇸🇦 Arábia Saudita",
    "🇩🇿 Argélia",
    "🇦🇷 Argentina",
    "🇦🇺 Austrália",
    "🇦🇹 Áustria",
    "🇧🇪 Bélgica",
    "🇧🇦 Bósnia e Herzegovina",
    "🇧🇷 Brasil",
    "🇨🇻 Cabo Verde",
    "🇶🇦 Catar",
    "🇨🇴 Colômbia",
    "🇨🇮 Costa do Marfim",
    "🇭🇷 Croácia",
    "🇨🇼 Curacao",
    "🇪🇬 Egito",
    "🇪🇨 Equador",
    "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Escócia",
    "🇪🇸 Espanha",
    "🇫🇷 França",
    "🇬🇭 Gana",
    "🇭🇹 Haiti",
    "🇳🇱 Holanda",
    "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra",
    "🇮🇶 Iraque",
    "🇯🇵 Japão",
    "🇯🇴 Jordânia",
    "🇲🇦 Marrocos",
    "🇳🇴 Noruega",
    "🇳🇿 Nova Zelândia",
    "🇵🇦 Panamá",
    "🇵🇾 Paraguai",
    "🇵🇹 Portugal",
    "🇨🇩 RD do Congo",
    "🇰🇷 República da Coreia",
    "🇮🇷 RI do Irã",
    "🇸🇳 Senegal",
    "🇸🇪 Suécia",
    "🇨🇭 Suíça",
    "🇨🇿 Tchéquia",
    "🇹🇳 Tunísia",
    "🇹🇷 Turquia",
    "🇺🇾 Uruguai",
    "🇺🇿 Uzbequistão"
]
